{{- if .Values.hyveConfig.create }}
apiVersion: hyve.io/v1alpha1
kind: HyveConfig
metadata:
  name: {{ .Values.configName }}
  namespace: {{ .Values.namespace }}
spec:
  strictResourceDelete: {{ .Values.hyveConfig.strictResourceDelete }}
  {{- if .Values.hyveConfig.defaultWorkflowImage }}
  defaultWorkflowImage: {{ .Values.hyveConfig.defaultWorkflowImage }}
  {{- end }}
{{- end }}
